# Generated by Django 6.0 on 2025-12-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite seu nome completo.', max_length=50, verbose_name='Nome')),
                ('idade', models.IntegerField(help_text='Digite sua idade:', verbose_name='idade')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1, verbose_name='Gênero')),
            ],
        ),
    ]
